### PR TITLE
Take last value from the array returned by the get_data functions

### PR DESCRIPTION
**Pull request by danielsjf**
Previously the first value was taken. This is the oldest value which is about a month ago for the 15 minute data query. It is now set to -1 which is the latest value.

### CODE REVIEW

**Comment by deanlyoung** [comment]
@danielsjf param ?limit=1&desc=true can also be used

**Comment by danielsjf** [comment]
Sweet, that's actually a cleaner solution as we limit the amount of data queried. Maybe we can open it up via a python argument which defaults to 1000.

**Comment by netmanchris** [comment]
Is there a reason we’re not using the current values instead of pulling from the 15 min average? API tier restriction maybe? wondering why this particular endpoint used?

**Comment by danielsjf** [comment]
Yes it is mostly due to the restriction (see discussion in the other issue).
Other than that, sometimes it is also slightly more convenient to have averages. For instance the dust measurements can fluctuate quite a bit so an instantaneous value might not be the best choice for monitoring.

**Comment by danielsjf** [comment]
In the last update, the AwairDev class has an argument to choose which value to take. Current, 5 min or 15 min. I personally use 15 min because of tier permissions.

**Comment by netmanchris** [comment]
LGTM

**Pull request merged**
